### ISSUE TITLE
Use of gzip

### ISSUE THREAD

**Issue by tseemann** [lskatz/Bio--Kmer#6]
1. i thought IO::Uncompress uses binaries or at elast `zlib` directly?
2. IO::Uncompress::Any might be easier
3. Naughty direct path - why not use `which("gzip")` to find the one in PATH first. eg conda or brew

```
    if(-e "/usr/bin/gzip"){
      open($fh,"gzip -cd $fastq | ") or die "ERROR: could not open $fastq for reading!: $!";
    }else{
      $fh=new IO::Uncompress::Gunzip($fastq) or die "ERROR: could not read $fastq: $!";
    }
```

**Comment by lskatz** [comment]
I'm still iffy on using IO::Uncompress right now because it is not core for earlier versions of Perl like v5.16.3 which is still the standard in CentOS7.

I added a check for the gzip location in da344ed.

**Comment by tseemann** [comment]
Oh, you are right about RHEL 7 (we use it)
`Summary of my perl5 (revision 5 version 16 subversion 3) configuration:`
Boom.
I use brew/conda perl.
