### ISSUE TITLE
Quoting shell metchars in system() calls

### ISSUE THREAD

**Issue by tseemann** [lskatz/Bio--Kmer#7]
`system("gzip -d -c $fastq")` = dangerous

use `"\Q$fastq\E"` or `quote_meta($fastq)`

**Comment by lskatz** [comment]
addressed in e6310c4

**Comment by tseemann** [comment]
Another way to get free quoting is to use the array syntax of `system()`
eg. `system("gzip", "-d", "-c", $fastq)`

**Comment by lskatz** [comment]
I had no idea that syntax was available!!!  Next time I will do it!

**Comment by tseemann** [comment]
_Ancora imparo_
